#!/bin/sh

function getTestFuncs {
	# local line=$(awk '/@Test/ {getline; print}' $1)#get line after @Test
	local line=$(awk -e '/(\/\*|\/\/)*@Test*(\*\/)?/,/\w+\(/ {print}' $1) 
	local fname=$(echo $line | grep -oE "\w*\w\(")  #extract func. name
	echo $(echo $fname | tr -d '(')                 #return name w/o `(`
}

function createRunTest {
	local md_name=${1%.*}
	local fname="${md_name##*/}"
	local tests=$(getTestFuncs $1)
	printf "\nvoid test_%s() { \n" $fname
	for test in "${tests[@]}"; do
		printf "  %s(); \n" $test
	done
	echo "  _Report(__PASS__, __FAIL__); "
	echo "} "
}

function removeLast {
	local argv=( "${@}" )
	local len=${#args[@]}
	unset argv[len-1];
	echo ${argv[@]}
}

function execCmd {
	local cmd=$1
	local file=${2##*/}
	local file_extension=".${file##*.}"
	local file_name="${file%.*}"
	if [ $file_extension == ".c" ]; then
		cp $2 ${2%/*}/$file_name.t.c
		createRunTest $2 >> ${2%/*}/$file_name.t.c
		#echo "$CC -o $file_name.o $cmd $file_name.c"
		#sh -c "$CC -o $file_name.o $cmd $file_name.t.c"
		#rm $file_name.t.c
	#else
		#echo "$CC $cmd ${file}"
		#sh -c "$CC $cmd ${file}"
	fi
}

#args=$(removeLast ${@};)
#printf -v cmd '%s ' "${args[@]}"
eval file=\${$#}; CC=gcc
#execCmd "$cmd" $file
execCmd , $file
